In [16]:
import pandas as pd

df=pd.read_csv('NISPUF17.csv')


df.columns

Index(['Unnamed: 0', 'SEQNUMC', 'SEQNUMHH', 'PDAT', 'PROVWT_D', 'RDDWT_D',
       'STRATUM', 'YEAR', 'AGECPOXR', 'HAD_CPOX',
       ...
       'XVRCTY2', 'XVRCTY3', 'XVRCTY4', 'XVRCTY5', 'XVRCTY6', 'XVRCTY7',
       'XVRCTY8', 'XVRCTY9', 'INS_STAT2_I', 'INS_BREAK_I'],
      dtype='object', length=454)

In [19]:
df['EDUC1'].unique()

array([4, 3, 1, 2])

In [28]:


df['EDUC1']

0        4
1        3
2        3
3        4
4        1
        ..
28460    3
28461    2
28462    3
28463    2
28464    4
Name: EDUC1, Length: 28465, dtype: int64

In [40]:
total = 0
len(df[df['EDUC1']==1])
#0.47974
#0.24588
#0.17235
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    result={"less than high school":len(df[df['EDUC1']==1])/len(df['EDUC1']),
            "high school":len(df[df['EDUC1']==2])/len(df['EDUC1']),
            "more than high school but not college":len(df[df['EDUC1']==3])/len(df['EDUC1']),
            "college":len(df[df['EDUC1']==4])/len(df['EDUC1'])
           }
    return result
proportion_of_education()

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [41]:
df['CBF_01'].unique()

array([ 1,  2, 99, 77])

In [62]:
df['P_NUMFLU'].unique()

df[(df['CBF_01']==2)]['P_NUMFLU'].dropna()

3        3.0
22       0.0
28       3.0
29       3.0
76       2.0
        ... 
28393    1.0
28397    4.0
28425    1.0
28447    1.0
28452    2.0
Name: P_NUMFLU, Length: 1997, dtype: float64

In [49]:
df['P_NUMFLU'].unique()



array([nan,  3.,  0.,  2.,  1.,  4.,  5.,  6.])

In [71]:
df[(df['CBF_01']==1)&(df['P_NUMFLU']>0.0)]

Unnamed: 0  SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  \
10             11   128211     12821     1  335.398714  198.123294     1057   
12             13   137041     13704     1   82.582116   45.544717     1051   
16             17   188611     18861     1  345.352030  196.111859     1057   
19             20   136171     13617     1  223.451930  136.912758     1059   
20             21   270401     27040     1  249.409773  188.752870     1066   
...           ...      ...       ...   ...         ...         ...      ...   
28436       28437    79531      7953     1   96.617497   54.463171     2065   
28437       28438   227671     22767     1  279.162013  120.371768     2052   
28438       28439   126141     12614     1  216.225073  126.221620     2052   
28446       28447   193801     19380     1  321.058203  110.009181     2047   
28449       28450   132081     13208     1  166.681363   96.330007     2059   

       YEAR  AGECPOXR  HAD_CPOX  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  \
10     2017       NaN         2  ...                        NaN      NaN   
12     2017       NaN         2  ...                        NaN      NaN   
16     2017       NaN         2  ...       VO               NaN      NaN   
19     2017       NaN         2  ...                        NaN      NaN   
20     2017       NaN         2  ...                        NaN      NaN   
...     ...       ...       ...  ...      ...      ...      ...      ...   
28436  2017       NaN         2  ...                        NaN      NaN   
28437  2017       NaN         2  ...                        NaN      NaN   
28438  2017       NaN         2  ...                        NaN      NaN   
28446  2017       NaN         2  ...                        NaN      NaN   
28449  2017       NaN         2  ...                        NaN      NaN   

       XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
10         NaN      NaN      NaN      NaN          1.0          2.0  
12         NaN      NaN      NaN      NaN          1.0          2.0  
16         NaN      NaN      NaN      NaN          1.0          2.0  
19         NaN      NaN      NaN      NaN          1.0          2.0  
20         NaN      NaN      NaN      NaN          2.0          2.0  
...        ...      ...      ...      ...          ...          ...  
28436      NaN      NaN      NaN      NaN          3.0          NaN  
28437      NaN      NaN      NaN      NaN          2.0          2.0  
28438      NaN      NaN      NaN      NaN          3.0          2.0  
28446      NaN      NaN      NaN      NaN          2.0          2.0  
28449      NaN      NaN      NaN      NaN          1.0          2.0  

[9825 rows x 454 columns]

In [73]:
df_no=df[(df['CBF_01']==2)&(df['P_NUMFLU']>0.0)]
df['CBF_01']

0        1
1        2
2        2
3        2
4        1
        ..
28460    2
28461    1
28462    1
28463    2
28464    1
Name: CBF_01, Length: 28465, dtype: int64

In [76]:
df['SEX']

0        1
1        1
2        2
3        2
4        2
        ..
28460    2
28461    2
28462    2
28463    2
28464    2
Name: SEX, Length: 28465, dtype: int64

In [77]:
df['P_NUMVRC'].unique()

array([nan,  1.,  0.,  2.,  3.])

In [78]:
df['HAD_CPOX'].unique()

array([ 2,  1, 77, 99])

In [82]:
df_yes=df[(df['HAD_CPOX']==1)&(df['P_NUMVRC']>=1.0)&(df['SEX']==2)]
df_no=df[(df['HAD_CPOX']==2)&(df['P_NUMVRC']>=1.0)&(df['SEX']==2)]
len(df_yes)/len(df_no)

0.0077918259335489565

In [83]:
def chickenpox_by_sex():
    temp = {"male":len(df[(df['HAD_CPOX']==1)&(df['P_NUMVRC']>=1.0)&(df['SEX']==1)])
           /(len(df[(df['HAD_CPOX']==2)&(df['P_NUMVRC']>=1.0)&(df['SEX']==1)])),
           "female":len(df[(df['HAD_CPOX']==1)&(df['P_NUMVRC']>=1.0)&(df['SEX']==2)])
           /(len(df[(df['HAD_CPOX']==2)&(df['P_NUMVRC']>=1.0)&(df['SEX']==2)]))}
    return temp
chickenpox_by_sex()

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [86]:
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    result={"less than high school":len(df[df['EDUC1']==1])/len(df['EDUC1']),
            "high school":len(df[df['EDUC1']==2])/len(df['EDUC1']),
            "more than high school but not college":len(df[df['EDUC1']==3])/len(df['EDUC1']),
            "college":len(df[df['EDUC1']==4])/len(df['EDUC1'])
           }
    return result
  

In [85]:
def average_influenza_doses():
    tup = (df[(df['CBF_01']==1)]['P_NUMFLU'].mean(),df[(df['CBF_01']==2)]['P_NUMFLU'].mean())
    return tup

In [87]:
df['HAD_CPOX'].unique()

array([ 2,  1, 77, 99])

In [88]:
df['P_NUMVRC'].unique()

array([nan,  1.,  0.,  2.,  3.])

In [128]:
had_chickenpox_column=df[(df['HAD_CPOX']==1)|(df['HAD_CPOX']==2)]['HAD_CPOX'].dropna()
num_chickenpox_vaccine_column=df[(df['P_NUMVRC']>0)]['P_NUMVRC'].dropna()

In [97]:
had_chickenpox_column=had_chickenpox_column.dropna()

In [98]:
num_chickenpox_vaccine_column=num_chickenpox_vaccine_column.dropna()

In [99]:
had_chickenpox_column.unique()

array([2, 1])

In [100]:
num_chickenpox_vaccine_column.unique()

array([1., 2., 3.])

In [129]:
df_final=pd.DataFrame({})
df_final['had_chickenpox_column']=had_chickenpox_column
df_final['num_chickenpox_vaccine_column']=num_chickenpox_vaccine_column

df_final.head()

had_chickenpox_column  num_chickenpox_vaccine_column
0                      2                            NaN
1                      2                            NaN
2                      2                            NaN
3                      2                            1.0
4                      2                            NaN

had_chickenpox_column  num_chickenpox_vaccine_column
0                          2                            0.0
1                          2                            0.0
2                          2                            0.0
3                          2                            1.0
4                          2                            0.0
...                      ...                            ...
28460                      2                            NaN
28461                      2                            NaN
28462                      2                            NaN
28463                      2                            NaN
28464                      2                            NaN

[28357 rows x 2 columns]

In [156]:
df_final['had_chickenpox_column'].unique()
    
import scipy.stats as stats
import numpy as np

print(len(df_final['had_chickenpox_column']))
print(len(df_final['num_chickenpox_vaccine_column']))
import math
num_chickenpox_vaccine_column=df_final['num_chickenpox_vaccine_column']
i=0
while i<len(num_chickenpox_vaccine_column):
    if(np.isnan(num_chickenpox_vaccine_column.iloc[i])):
        num_chickenpox_vaccine_column.iloc[i]=0
    i=i+1
df_final['num_chickenpox_vaccine_column']=num_chickenpox_vaccine_column

corr, pval=stats.pearsonr(df_final["had_chickenpox_column"],df_final["num_chickenpox_vaccine_column"])
corr


28357
28357


0.04391797462998481

In [158]:
had_chickenpox_column=df[(df['HAD_CPOX']==1)|(df['HAD_CPOX']==2)]['HAD_CPOX'].dropna()
num_chickenpox_vaccine_column=df[(df['P_NUMVRC']>0)]['P_NUMVRC'].dropna()
df_final=pd.DataFrame({})
df_final['had_chickenpox_column']=had_chickenpox_column
df_final['num_chickenpox_vaccine_column']=num_chickenpox_vaccine_column 
num_chickenpox_vaccine_column=df_final['num_chickenpox_vaccine_column']
num_chickenpox_vaccine_column

0        NaN
1        NaN
2        NaN
3        1.0
4        NaN
        ... 
28460    NaN
28461    NaN
28462    NaN
28463    NaN
28464    NaN
Name: num_chickenpox_vaccine_column, Length: 28357, dtype: float64

In [159]:
df_final.iloc[1]

had_chickenpox_column            2.0
num_chickenpox_vaccine_column    NaN
Name: 1, dtype: float64

In [169]:
del df_final.index[0]

AttributeError: __delitem__

In [170]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import math
    
    had_chickenpox_column=df[(df['HAD_CPOX']==1)|(df['HAD_CPOX']==2)]['HAD_CPOX'].dropna()
    num_chickenpox_vaccine_column=df[(df['P_NUMVRC']>0)]['P_NUMVRC'].dropna()
    
    df_final=pd.DataFrame({})
    df_final['had_chickenpox_column']=had_chickenpox_column
    df_final['num_chickenpox_vaccine_column']=num_chickenpox_vaccine_column
    num_chickenpox_vaccine_column=df_final['num_chickenpox_vaccine_column']
    i=0
    temp=df_final;
    while i<len(num_chickenpox_vaccine_column):
        if(np.isnan(num_chickenpox_vaccine_column.iloc[i])):
                temp= temp.drop(df_final.index[i])
            
        i=i+1
    df_final=temp
    
    corr, pval=stats.pearsonr(df_final["had_chickenpox_column"],df_final["num_chickenpox_vaccine_column"])
    return corr

   
corr_chickenpox()    




-0.01333708188640046

In [171]:
df1 = df[(df['HAD_CPOX']==1)|(df['HAD_CPOX']==2)]

In [172]:
df1=df1[]

Unnamed: 0  SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  \
3               4    86131      8613     1  675.430817  333.447418     1040   
4               5   227141     22714     1  482.617748  278.768063     1008   
6               7   221381     22138     1  516.427723  248.916038     1008   
7               8   182861     18286     1  313.225832  163.213401     1001   
8               9   161121     16112     1  978.042448  718.616990     1016   
...           ...      ...       ...   ...         ...         ...      ...   
28446       28447   193801     19380     1  321.058203  110.009181     2047   
28447       28448   136841     13684     1  593.426753  337.255316     2031   
28449       28450   132081     13208     1  166.681363   96.330007     2059   
28452       28453    82151      8215     1  335.456813  159.895243     2056   
28454       28455   191451     19145     1   59.626969   29.187316     2074   

       YEAR  AGECPOXR  HAD_CPOX  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  \
3      2017       NaN         2  ...                        NaN      NaN   
4      2017       NaN         2  ...                        NaN      NaN   
6      2017       NaN         2  ...                        NaN      NaN   
7      2017       NaN         2  ...                        NaN      NaN   
8      2017       3.0         1  ...                        NaN      NaN   
...     ...       ...       ...  ...      ...      ...      ...      ...   
28446  2017       NaN         2  ...                        NaN      NaN   
28447  2017       NaN         2  ...                        NaN      NaN   
28449  2017       NaN         2  ...                        NaN      NaN   
28452  2017       NaN         2  ...                        NaN      NaN   
28454  2017       NaN         2  ...                        NaN      NaN   

       XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
3          NaN      NaN      NaN      NaN          1.0          2.0  
4          NaN      NaN      NaN      NaN          2.0          1.0  
6          NaN      NaN      NaN      NaN          1.0          2.0  
7          NaN      NaN      NaN      NaN          3.0          2.0  
8          NaN      NaN      NaN      NaN          4.0          4.0  
...        ...      ...      ...      ...          ...          ...  
28446      NaN      NaN      NaN      NaN          2.0          2.0  
28447      NaN      NaN      NaN      NaN          1.0          2.0  
28449      NaN      NaN      NaN      NaN          1.0          2.0  
28452      NaN      NaN      NaN      NaN          1.0          2.0  
28454      NaN      NaN      NaN      NaN          3.0          2.0  

[15333 rows x 454 columns]